language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
addons:
  postgresql: "9.6"
services:
  - postgresql
  - mysql
install:
  - pip install peewee psycopg2 pymysql colorama
script:
  - python test.py PostgreSQL
  - python test.py MySQL

